### ISSUE TITLE
Error: Invalid request - only 65535 characters are allowed

### ISSUE THREAD

**Issue by tandeday** [NasAmin/trx-parser#68]
I am kicking the tires on this action using a project with about 1000 tests.  Unfortunately it fails.  Any suggestions?

```
Finding Trx files in: /home/runner/work/mit-yousee-odin-api/mit-yousee-odin-api/TestResults
Files count: 1
Processing 1 trx files
Transforming file /home/runner/work/mit-yousee-odin-api/mit-yousee-odin-api/TestResults/_fv-az186-920_2020-12-28_08_37_52.trx
Checking for failing tests
Creating PR check for ODINAPI SELFCARE.TESTS
Creating status check for GitSha: 97c859732655f4633222f0db3b6483c07ab21e70 on a push event
Check time is: Mon, 28 Dec 2020 08:38:34 GMT
Error: Invalid request.

Only 65535 characters are allowed; 1607778 were supplied.
```

**Comment by NasAmin** [comment]
Hi @tandeday 
Thanks for trying to ye this action and raising this issue. I am currently on vacation but from the error I can guess that it is failing due to limits on the outcome text of the checks api.

Not sure what can b done about that but I'll have a look next week.

In the meantime, would you mind sharing the trx if not confidential?

**Comment by NasAmin** [comment]
github/docs/#2403

**Comment by tandeday** [comment]
This is not urgent so no rush.  I cannot share the TRX file publicly, but perhaps with you personally.  Let's have a look together when you are back from vacation.

**Comment by NasAmin** [comment]
Related: zyborg/dotnet-tests-report#6

**Comment by NasAmin** [comment]
@tandeday Based on the linked issues in the comment above it is clear this is a hard limit on the GitHub checks API and there is not solution to that limit.

**So here's what I propose:**
* Allow skipping creation of test report with a new flag `skip_test_report` and create an empty check with a simple overall pass or fail status. OR
* Introduce a new flag that allows to only create a report when there are failing tests otherwise just show the overall status of passed.
* Don't introduce any flags but in the logic work out if the number of characters in the test report exceed the limit. Then automatically:
  * Only show failing tests on the report
  * show overall status of passed if there are no failing tests.

Thoughts?

Once we have some consensus on one of options above or a better option you could suggest then we can talk about implementation. Please feel free to contribute if you have time otherwise I'll try to address this when I can find free time.

**Comment by tandeday** [comment]
Things have changed as we have had a firing round, and this is no longer in scope.  I will suggest that the default behavior is the safest without generating a test report (or at least just create a summary that will fit in the block), and that the full report is only shown if explicitly enabled, and that the documentation clearly shows that there is a hard limit for the size.

Thanks

**Comment by NasAmin** [comment]
Created a new release https://github.com/NasAmin/trx-parser/releases/tag/v0.1.0
From `v0.1.0` onwards, `trx-parser` will only report failed tests
